@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor User
participant Login
database  Database
activate User
activate Login
User -> Login: Visit
User -> Login : Enter email/phone/password
note left: или лучше loop
note right: или лучше разделить мыло и телефон на кейсы
alt validate data in client side
    Login -> Login: Checking the email input is correct
    Login -> Login: Checking the phone input is correct
    Login -> User: Correct message
||45||
else incorrect input email/phone
    Login -> Login: Email input verification is incorrect
    Login -> Login: Phone input verification is incorrect
    Login -> User: incorrect message
||45||
end
deactivate Login
User -> Login : login()
activate Login
Login -> Database: Send email/phone/password hash
deactivate Login
activate Database
Database -> Database: Validate user data

alt successful case user data is correct
    Database --> Login : User data accepted
    deactivate Database
    activate Login
    Login -> Login : Redirect
    Login --> User: Accepted()
    deactivate Login
    deactivate User
||45||
else user data incorrect
    Database --> Login: User data rejected
    Login -> Login: Redirect
    Login --> User: invalid message()
||45||
else cookie is not set
    Database --> Login: cookie is not set
    Login --> User: 401 status message
||45||
end

@enduml