@startuml
'https://plantuml.com/sequence-diagram

autonumber
title User login sequence diagram
actor User
participant Login
database  Database
activate User
activate Login

skinparam sequenceMessageAlign center

User -> Login: Visit
User -> Login : Enter email/phone/password
== Client side validation ==
note left: или лучше loop
note right: или лучше разделить мыло и телефон на кейсы
alt validate data in client side
    Login -> Login: Checking the email input is correct
    Login -> Login: Checking the phone input is correct
    Login -> Login: Checking the password input is correct
    Login -> User: Correct
||45||
else incorrect input email/phone
    Login -> Login: Email input verification is incorrect
    Login -> User: incorrect message \n <<Провверьте правильность email>>
    Login -> Login: Phone input verification is incorrect
    Login -> User: incorrect message \n <<Телефон только RUS/MN>>
    Login -> Login: Password input verification is incorrect
    Login -> User: incorrect message \n <<Пароль должен быть не менее 4 символов>>
||45||
end

deactivate Login
User -> Login : login()

activate Login
Login -> Database: Send email/phone/password hash
== Server side validation ==
deactivate Login

activate Database
Database -> Database: Validate user data

alt successful case user data is correct
    Database --> Login : User data accepted
    deactivate Database
    activate Login
    Login -> Login : Redirect
    Login --> User: Accepted()<<Вот ваш кот>>
    deactivate Login
    deactivate User
||45||
else user data incorrect
    Database --> Login: User data rejected
    Login -> Login: Redirect
    note left: осветить ли проверку существования пользователя\n или сразу писать что котик недоступен\n на сколько умен сервер?
    Login --> User: invalid message() <<Котики не для вас или вы ввели не правильные данные>>
    Login --> User: clear password field()
||45||
else cookie is not set
    Database --> Login: cookie is not set
    Login --> User: status(401) <<401 status message>>
||45||
end

@enduml