@startuml
'https://plantuml.com/sequence-diagram

autonumber
title User login sequence diagram
actor User
participant SPA
participant Server
database  Database
activate User


skinparam sequenceMessageAlign center
skinparam style strictuml


User -> SPA : Enter email/phone/password
== Client side validation ==

alt validate data in client side
    SPA -> SPA: Checking the email input is correct
    SPA -> SPA: Checking the phone input is correct
    SPA -> SPA: Checking the password input is correct
    SPA --> User: Correct
||45||
else incorrect input email/phone
    SPA -> SPA: Email input verification is incorrect
    SPA --> User: incorrect message \n <<Провверьте правильность формата email>>
    SPA -> SPA: Phone input verification is incorrect
    SPA --> User: incorrect message \n <<Телефон только RUS/MN>>
    SPA -> SPA: Password input verification is incorrect
    SPA --> User: incorrect message \n <<Пароль должен быть не менее 4 символов>>
||45||
end

deactivate SPA
User -> SPA : login()

activate SPA
SPA -> Server: Send email/phone/password hash
== Server side validation ==
deactivate SPA

activate Server
Server -> Database: query data()
activate Database
Database --> Server: email verify/password_verify()
deactivate Database

alt successful case user data is correct
    Server -> Server: Validate and comparison user data
    Server -> SPA : User data accepted
    activate SPA
    Server -> Server: session_start()
    Server -> Server: Set-Cookie
    Server --> SPA: Send Cookie
    deactivate Server
    SPA <-- SPA: Save cookie
    SPA -> SPA : Redirect
    SPA --> User: Accepted()<<Вот ваш кот>>
    deactivate SPA
    deactivate User
||45||
else user data incorrect
    Server --> SPA: User data rejected invalid password 403 error
    SPA -> SPA: Redirect
    SPA --> User: invalid message() <<Котик не для вас или вы ввели не правильный пароль>>
    SPA --> User: clear password field()
||45||
else user data does not exist
    Server --> SPA: User email/phone does not exist 403 error
    SPA -> SPA: Redirect
    SPA --> User: invalid message() <<Такого пользователя не существует>>
    SPA --> User: clear password field()
||45||
else cookie is not set
    Server --> SPA: cookie is not set
    SPA --> User: status(401) <<401 status message>>
||45||
end

@enduml